### ISSUE TITLE
Crash bug in events.js: unspecified 'error' event.

### ISSUE THREAD

**Issue by neuhaus** [jfd/wpilot#23]
This bug was triggered twice on my server:

events.js:70
        throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at WebSocket.EventEmitter.emit (events.js:70:15)
    at Receiver.self._receiver.onerror (.../wpilot/node_modules/ws/lib/WebSocket.js:561:10)
    at Receiver.error (...wpilot/node_modules/ws/lib/Receiver.js:301:8)
    at Receiver.opcodes.8.finish (.../wpilot/node_modules/ws/lib/Receiver.js:497:14)
    at Receiver.opcodes.8.getData (.../wpilot/node_modules/ws/lib/Receiver.js:478:33)
    at Receiver.add (.../wpilot/node_modules/ws/lib/Receiver.js:93:24)
    at Socket.firstHandler (.../wpilot/node_modules/ws/lib/WebSocket.js:519:22)
    at Socket.EventEmitter.emit (events.js:93:17)
    at TCP.onread (net.js:396:14)

**Comment by kim07** [comment]
same issue

**Comment by neuhaus** [comment]
I put a try catch around it...
